services:
  db:
    image: postgres:16
    container_name: auth_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - auth_net

  migrator:
    build: ./docker/migrator
    container_name: auth_migrator
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}
    networks:
      - auth_net


  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
      target: dev
    container_name: auth_backend
    depends_on:
      db:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - auth_net
    volumes:
      - ./docker/backend/src:/app/src
      - ./docker/backend/package.json:/app/package.json
      #- /app/node_modules
    environment:
      - DB_URL=${DB_URL}
      - NODE_ENV=${NODE_ENV}

volumes:
  db_data:

networks:
  auth_net:
